### ISSUE TITLE
Help real case implementation

### ISSUE THREAD

**Issue by agungsugiarto** [sribna/licensor#3]
Hello @sribna thanks for your great package.  I have plans to use this package, both [license](https://github.com/sribna/licensee) and [licensor](https://github.com/sribna/licensor) Is there an example repo to use this package.  Thank you

**Comment by cool-raju** [comment]
Hello @agungsugiarto 
Did you find any example repo?? Then please help me. And also this is not downloaded through composer. Error occurs
